const http = require('node:http');
const players = new Map();
let nextId = 1;
function send(res, code, data, headers = {}) { const body = data === undefined ? '' : JSON.stringify(data); res.writeHead(code, { 'content-type': 'application/json; charset=utf-8', ...headers, ...(body ? { 'content-length': Buffer.byteLength(body) } : {}) }); res.end(body); }
function read(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', (chunk) => { raw += chunk; }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('JSON inválido')); } }); }); }
function createServer() { return http.createServer(async (req, res) => { const url = new URL(req.url, 'http://localhost'); const match = url.pathname.match(/^\/api\/players\/([^/]+)$/); try { if (req.method === 'GET' && url.pathname === '/api/players') return send(res, 200, { ok: true, data: [...players.values()] }); if (req.method === 'POST' && url.pathname === '/api/players') { const body = await read(req); if (!body.name?.trim()) return send(res, 400, { ok: false, error: 'name es obligatorio' }); if ([...players.values()].some((p) => p.name.toLowerCase() === body.name.trim().toLowerCase())) return send(res, 409, { ok: false, error: 'El jugador ya existe' }); const player = { id: nextId++, name: body.name.trim(), team: body.team?.trim() || 'sin equipo' }; players.set(String(player.id), player); return send(res, 201, { ok: true, data: player }, { location: '/api/players/' + player.id }); } if (req.method === 'DELETE' && match) { if (!players.has(match[1])) return send(res, 404, { ok: false, error: 'Jugador no encontrado' }); players.delete(match[1]); res.writeHead(204); return res.end(); } if (url.pathname.startsWith('/api/')) return send(res, 405, { ok: false, error: 'Método no permitido' }, { allow: 'GET, POST, DELETE' }); return send(res, 404, { ok: false, error: 'Ruta no encontrada' }); } catch (error) { return send(res, 400, { ok: false, error: error.message }); } }); }
function start(port = Number(process.env.PORT || 3000)) { const server = createServer(); server.listen(port, () => console.log('API de jugadores en http://localhost:' + port)); return server; }
if (require.main === module) start();
module.exports = { createServer, start };
