const http = require('node:http');
const orders = new Map([[1, { id: 1, customer: 'Taller Centro', service: 'Mantenimiento', status: 'en proceso' }]]);
function send(res, code, data) { const body = data === undefined ? '' : JSON.stringify(data); res.writeHead(code, { 'content-type': 'application/json; charset=utf-8', ...(body ? { 'content-length': Buffer.byteLength(body) } : {}) }); res.end(body); }
function read(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', (chunk) => { raw += chunk; }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('JSON inválido')); } }); }); }
function createOrder(input) { if (!input?.customer?.trim() || !input?.service?.trim()) throw new Error('customer y service son obligatorios'); const id = Math.max(0, ...orders.keys()) + 1; const order = { id, customer: input.customer.trim(), service: input.service.trim(), status: 'pendiente' }; orders.set(id, order); return order; }
function createServer() { return http.createServer(async (req, res) => { const url = new URL(req.url, 'http://localhost'); const match = url.pathname.match(/^\/api\/orders\/([^/]+)$/); try { if (req.method === 'GET' && url.pathname === '/health') return send(res, 200, { ok: true }); if (req.method === 'GET' && url.pathname === '/api/orders') return send(res, 200, { ok: true, data: [...orders.values()] }); if (req.method === 'GET' && match) { const order = orders.get(Number(match[1])); return order ? send(res, 200, { ok: true, data: order }) : send(res, 404, { ok: false, error: 'Orden no encontrada' }); } if (req.method === 'POST' && url.pathname === '/api/orders') return send(res, 201, { ok: true, data: createOrder(await read(req)) }); return send(res, 404, { ok: false, error: 'Ruta no encontrada' }); } catch (error) { return send(res, 400, { ok: false, error: error.message }); } }); }
function start(port = Number(process.env.PORT || 3000)) { const server = createServer(); server.listen(port, process.env.HOST || '127.0.0.1', () => console.log('Taller API en http://localhost:' + port)); return server; }
if (require.main === module) start();
module.exports = { createServer, start };
