const http = require('node:http');
const jumps = []; let nextId = 1;
function sendJson(res, status, data) { const body = JSON.stringify(data); res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'content-length': Buffer.byteLength(body) }); res.end(body); }
function readJson(req, maxBytes = 10000) { return new Promise((resolve, reject) => { let raw = ''; let size = 0; let tooLarge = false; req.setEncoding('utf8'); req.on('data', (chunk) => { size += Buffer.byteLength(chunk); if (size > maxBytes) tooLarge = true; else raw += chunk; }); req.on('end', () => { if (tooLarge) return reject(Object.assign(new Error('El cuerpo es demasiado grande'), { statusCode: 413 })); try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(Object.assign(new Error('El cuerpo debe ser JSON válido'), { statusCode: 400 })); } }); req.on('error', reject); }); }
function validate(body) { if (!body?.jumper?.trim()) return 'jumper es obligatorio'; if (!Number.isFinite(body.altitude) || body.altitude < 100 || body.altitude > 10000) return 'altitude debe estar entre 100 y 10000'; return null; }
function createServer() { return http.createServer(async (req, res) => { const url = new URL(req.url, 'http://localhost'); if (req.method === 'GET' && url.pathname === '/api/jumps') return sendJson(res, 200, { ok: true, data: jumps }); if (req.method === 'POST' && url.pathname === '/api/jumps') { try { const body = await readJson(req); const error = validate(body); if (error) return sendJson(res, 400, { ok: false, error }); const jump = { id: nextId++, jumper: body.jumper.trim(), altitude: body.altitude }; jumps.push(jump); return sendJson(res, 201, { ok: true, data: jump }, { location: `/api/jumps/${jump.id}` }); } catch (error) { return sendJson(res, error.statusCode || 500, { ok: false, error: error.message }); } } if (url.pathname.startsWith('/api/')) return sendJson(res, 405, { ok: false, error: 'Método no permitido' }); return sendJson(res, 404, { ok: false, error: 'Ruta no encontrada' }); }); }
function start(port = Number(process.env.PORT || 3000)) { const server = createServer(); server.listen(port, () => console.log(`API de paracaidismo en http://localhost:${port}`)); return server; }
if (require.main === module) start();
module.exports = { readJson, validate, createServer, start };
